#!/usr/bin/env bash
# =============================================================================
# 09 — n8n Workflow Automation Setup
# Docker Compose stack: n8n + PostgreSQL on NVMe, Tailscale Funnel for webhooks
# =============================================================================
set -euo pipefail

# shellcheck source=../lib/common.sh
source "$(dirname "$0")/../lib/common.sh"

N8N_DIR="${NVME_MOUNT}/n8n"
N8N_ENV="${N8N_DIR}/.env"
N8N_COMPOSE="${N8N_DIR}/docker-compose.yml"

# ---------------------------------------------------------------------------
# Prerequisites
# ---------------------------------------------------------------------------
if ! command -v docker &>/dev/null; then
    err "Docker not installed — run step 5 first"
    exit 1
fi

if ! docker compose version &>/dev/null 2>&1; then
    err "Docker Compose V2 not available — run step 5 first"
    exit 1
fi

if ! mountpoint -q "$NVME_MOUNT" 2>/dev/null; then
    err "NVMe not mounted at ${NVME_MOUNT} — run step 4 first"
    exit 1
fi

# ---------------------------------------------------------------------------
# Create directories
# ---------------------------------------------------------------------------
mkdir -p "${N8N_DIR}/data" "${N8N_DIR}/postgres" "${N8N_DIR}/workflows"
chown -R "${REAL_USER}:${REAL_USER}" "${N8N_DIR}"
log "n8n directories created: ${N8N_DIR}/{data,postgres,workflows}"

# ---------------------------------------------------------------------------
# Generate .env (only if not exists — preserves secrets across re-runs)
# ---------------------------------------------------------------------------
if [[ ! -f "$N8N_ENV" ]]; then
    N8N_DB_PASS=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32)
    N8N_ENCRYPTION_KEY=$(openssl rand -hex 32)

    # Determine webhook URL
    N8N_WEBHOOK_URL="http://localhost:5678/"
    if command -v tailscale &>/dev/null && tailscale status &>/dev/null 2>&1; then
        TS_HOSTNAME=$(tailscale status --json 2>/dev/null | jq -r '.Self.DNSName' | sed 's/\.$//')
        if [[ -n "$TS_HOSTNAME" && "$TS_HOSTNAME" != "null" ]]; then
            N8N_WEBHOOK_URL="https://${TS_HOSTNAME}:5678/"
        fi
    fi

    cat > "$N8N_ENV" << EOF
# n8n Docker Stack — generated by 09-n8n-setup.sh
# Generated: $(date -Iseconds)

# Database
N8N_DB_USER=n8n
N8N_DB_PASS=${N8N_DB_PASS}

# Security
N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}

# Network
N8N_HOST=0.0.0.0
N8N_BIND_ADDRESS=0.0.0.0
N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
EOF

    chmod 600 "$N8N_ENV"
    chown "${REAL_USER}:${REAL_USER}" "$N8N_ENV"
    log "n8n .env generated with secure random credentials"
    warn "BACKUP the encryption key! Without it, credentials in n8n are lost."
    warn "  cat ${N8N_ENV}"
else
    skip "n8n .env already exists (secrets preserved)"
fi

# ---------------------------------------------------------------------------
# Copy docker-compose.yml
# ---------------------------------------------------------------------------
COMPOSE_SRC="${SCRIPT_DIR}/config/n8n/docker-compose.yml"
if [[ ! -f "$N8N_COMPOSE" ]] || ! diff -q "$COMPOSE_SRC" "$N8N_COMPOSE" &>/dev/null; then
    cp "$COMPOSE_SRC" "$N8N_COMPOSE"
    chown "${REAL_USER}:${REAL_USER}" "$N8N_COMPOSE"
    log "docker-compose.yml deployed to ${N8N_DIR}"
else
    skip "docker-compose.yml already up to date"
fi

# ---------------------------------------------------------------------------
# UFW: allow n8n port on LAN
# ---------------------------------------------------------------------------
if command -v ufw &>/dev/null && ufw status | grep -q "active"; then
    if ! ufw status | grep -q "5678"; then
        # Get LAN subnet from default interface
        DEFAULT_IFACE=$(ip route show default 2>/dev/null | awk '/default/{print $5; exit}')
        LAN_SUBNET=$(ip -4 addr show "$DEFAULT_IFACE" 2>/dev/null | grep -oP '(?<=inet\s)\d+(\.\d+){3}/\d+' | head -1)

        if [[ -n "$LAN_SUBNET" ]]; then
            # Convert to network address (e.g. 192.168.1.50/24 -> 192.168.1.0/24)
            NETWORK=$(ipcalc -n "$LAN_SUBNET" 2>/dev/null | grep -oP '\d+(\.\d+){3}' || echo "")
            PREFIX=$(echo "$LAN_SUBNET" | grep -oP '/\d+')

            if [[ -n "$NETWORK" ]]; then
                ufw allow from "${NETWORK}${PREFIX}" to any port 5678 proto tcp comment 'n8n Web UI (LAN only)'
                log "UFW: port 5678 allowed from ${NETWORK}${PREFIX}"
            else
                # Fallback: allow from any (still behind firewall)
                ufw allow 5678/tcp comment 'n8n Web UI'
                log "UFW: port 5678 allowed (could not determine LAN subnet)"
            fi
        else
            ufw allow 5678/tcp comment 'n8n Web UI'
            log "UFW: port 5678 allowed"
        fi
    else
        skip "UFW rule for port 5678 already exists"
    fi
fi

# ---------------------------------------------------------------------------
# Pull images and start stack
# ---------------------------------------------------------------------------
log "Pulling Docker images (this may take a few minutes)..."
cd "$N8N_DIR"
sudo -u "$REAL_USER" docker compose pull

log "Starting n8n stack..."
sudo -u "$REAL_USER" docker compose up -d

# Wait for n8n to be healthy
info "Waiting for n8n to start..."
for i in $(seq 1 30); do
    if curl -s --connect-timeout 2 http://localhost:5678/healthz &>/dev/null; then
        log "n8n is running at http://localhost:5678"
        break
    fi
    if [[ $i -eq 30 ]]; then
        warn "n8n did not respond within 30s — check: docker compose -f ${N8N_COMPOSE} logs"
    fi
    sleep 1
done

# ---------------------------------------------------------------------------
# Backup: encryption key
# ---------------------------------------------------------------------------
BACKUP_DIR="${NVME_MOUNT}/backups/n8n"
mkdir -p "$BACKUP_DIR"
chown "${REAL_USER}:${REAL_USER}" "$BACKUP_DIR"

ENCRYPTION_KEY_BACKUP="${BACKUP_DIR}/encryption-key.txt"
if [[ ! -f "$ENCRYPTION_KEY_BACKUP" ]]; then
    grep "N8N_ENCRYPTION_KEY" "$N8N_ENV" > "$ENCRYPTION_KEY_BACKUP"
    chmod 600 "$ENCRYPTION_KEY_BACKUP"
    chown "${REAL_USER}:${REAL_USER}" "$ENCRYPTION_KEY_BACKUP"
    log "Encryption key backed up to ${ENCRYPTION_KEY_BACKUP}"
else
    skip "Encryption key backup already exists"
fi

# ---------------------------------------------------------------------------
# Cron: daily workflow export
# ---------------------------------------------------------------------------
CRON_WORKFLOW="/etc/cron.daily/n8n-workflow-export"
if [[ ! -f "$CRON_WORKFLOW" ]]; then
    cat > "$CRON_WORKFLOW" << 'CRONEOF'
#!/bin/bash
# Export all n8n workflows as JSON files for backup
N8N_DIR="/mnt/nvme/n8n"
EXPORT_DIR="${N8N_DIR}/workflows"
COMPOSE="${N8N_DIR}/docker-compose.yml"

if ! docker compose -f "$COMPOSE" ps --status running 2>/dev/null | grep -q n8n; then
    exit 0
fi

docker compose -f "$COMPOSE" exec -T n8n n8n export:workflow \
    --all --separate --output=/home/node/workflows/ 2>/dev/null || true
CRONEOF
    chmod +x "$CRON_WORKFLOW"
    log "Cron installed: daily workflow export"
else
    skip "Workflow export cron already exists"
fi

# ---------------------------------------------------------------------------
# Cron: weekly PostgreSQL backup
# ---------------------------------------------------------------------------
CRON_PGDUMP="/etc/cron.weekly/n8n-pg-backup"
if [[ ! -f "$CRON_PGDUMP" ]]; then
    cat > "$CRON_PGDUMP" << 'CRONEOF'
#!/bin/bash
# Weekly PostgreSQL dump for n8n
N8N_DIR="/mnt/nvme/n8n"
BACKUP_DIR="/mnt/nvme/backups/n8n"
COMPOSE="${N8N_DIR}/docker-compose.yml"

if ! docker compose -f "$COMPOSE" ps --status running 2>/dev/null | grep -q postgres; then
    exit 0
fi

mkdir -p "$BACKUP_DIR"
DUMP_FILE="${BACKUP_DIR}/n8n-postgres-$(date +%Y%m%d).sql.gz"

# Source n8n .env for DB credentials
set -a
source "${N8N_DIR}/.env" 2>/dev/null
set +a

docker compose -f "$COMPOSE" exec -T postgres \
    pg_dump -U "${N8N_DB_USER:-n8n}" -d n8n 2>/dev/null | gzip > "$DUMP_FILE"

# Keep only last 4 weekly backups
ls -t "${BACKUP_DIR}"/n8n-postgres-*.sql.gz 2>/dev/null | tail -n +5 | xargs -r rm --
CRONEOF
    chmod +x "$CRON_PGDUMP"
    log "Cron installed: weekly PostgreSQL backup"
else
    skip "PostgreSQL backup cron already exists"
fi

# ---------------------------------------------------------------------------
# Tailscale serve & funnel (optional)
# ---------------------------------------------------------------------------
if command -v tailscale &>/dev/null && tailscale status &>/dev/null 2>&1; then
    # Serve n8n UI over Tailscale (VPN access)
    tailscale serve --bg 5678 2>/dev/null || true
    log "Tailscale serve: n8n accessible over VPN"

    # Funnel only webhook paths (public access for external triggers)
    tailscale funnel --bg --set-path /webhook 5678 2>/dev/null || true
    log "Tailscale funnel: /webhook/* exposed publicly"

    TS_HOSTNAME=$(tailscale status --json 2>/dev/null | jq -r '.Self.DNSName' | sed 's/\.$//')
    if [[ -n "$TS_HOSTNAME" && "$TS_HOSTNAME" != "null" ]]; then
        info "n8n via Tailscale: https://${TS_HOSTNAME}"
        info "Webhooks: https://${TS_HOSTNAME}/webhook/<id>"
    fi
else
    info "Tailscale not available — n8n accessible on LAN only"
    info "Install Tailscale for remote access: INSTALL_TAILSCALE=true in .env"
fi

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
log "n8n setup complete"
log "  Web UI:     http://localhost:5678"
log "  Data:       ${N8N_DIR}/data"
log "  Database:   ${N8N_DIR}/postgres"
log "  Workflows:  ${N8N_DIR}/workflows"
log "  Compose:    ${N8N_COMPOSE}"
log "  Env:        ${N8N_ENV}"
echo ""
info "Next steps:"
info "  1. Open http://<jetson-ip>:5678 in your browser"
info "  2. Create your owner account (first-time setup)"
info "  3. Enable 2FA in Settings -> Personal"
info "  4. Generate an API key in Settings -> API"
